name: mrs
channels:
  - conda-forge
  - defaults
dependencies:
  - urllib3==1.24.2
  - pandas
  - numpy
  - scipy
  - pylint
  - dash==1.12.0
  - dash-core-components==1.10.0         
  - dash-html-components==1.0.3
  - kaggle==1.5.6
  - scikit-learn
  - gunicorn
  - pathlib
